language: r
sudo: true
cache: 
  packages: true
  timeout: 6000
warnings_are_errors: false

# Environment variables for builds
env:
  global:
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - _R_CHECK_FORCE_SUGGESTS_=false

# Avoid building vignettes
r_build_args: --no-build-vignettes --no-manual

r:
  - release

# Code coverage
r_packages:
  - covr

# Report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
